# Generated by Django 3.2.12 on 2022-02-08 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20220207_1115'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disputes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000)),
                ('resolved', models.CharField(choices=[('No', 'Unresolved'), ('Yes', 'Resolved')], default='No', max_length=20)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.event')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='payments.payment')),
            ],
        ),
    ]
