# Generated by Django 3.2.12 on 2022-02-08 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20220207_1115'),
        ('payments', '0002_disputes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Disputes',
            new_name='Dispute',
        ),
    ]
