# Generated by Django 3.2.12 on 2022-03-22 03:49

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linked_in', models.CharField(blank=True, max_length=200, null=True)),
                ('fb', models.CharField(blank=True, max_length=200, null=True)),
                ('insta', models.CharField(blank=True, max_length=200, null=True)),
                ('portfolio', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Exhibit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('likes', models.IntegerField(default=0)),
                ('content', models.TextField()),
                ('image', models.FileField(default='img_avatar.jpg', upload_to='exhibition')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exhibitions.artist')),
            ],
        ),
    ]
