# Generated by Django 3.2.12 on 2022-02-07 05:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.CharField(max_length=100)),
                ('contact', models.CharField(default='0000000000', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(default='0000000000', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github', models.CharField(max_length=100)),
                ('linked_in', models.CharField(max_length=100)),
                ('fb', models.CharField(max_length=100)),
                ('insta', models.CharField(max_length=100)),
                ('photo', models.FileField(default='img_avatar.jpg', upload_to='developer')),
                ('contact', models.CharField(default='0000000000', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Core',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=100)),
                ('github', models.CharField(default='', max_length=100)),
                ('linked_in', models.CharField(default='', max_length=100)),
                ('fb', models.CharField(default='', max_length=100)),
                ('insta', models.CharField(default='', max_length=100)),
                ('photo', models.FileField(default='img_avatar.jpg', upload_to='core')),
                ('contact', models.CharField(default='0000000000', max_length=10)),
                ('department', models.CharField(max_length=100, null=True)),
                ('work', models.CharField(max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
