# Generated by Django 3.2.12 on 2022-02-18 16:33

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('image_id', models.IntegerField(default=home.models.get_default_gallery_id, primary_key=True, serialize=False)),
                ('image', models.FileField(upload_to='gallery')),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
